PNGS = active.png activity.png addfren.png add.png add_to_cart.png auto.png befren.png blend.png boss.png bread.png buy.png cam.png capture.png claim.png clear.png close.png comms.png conf.png created.png crew.png crewsize.png dashgt.png doc.png don.png email.png encode.png enc.png fam.png file.png fren.png frens.png gen_nom.png get.png go.png goto.png grid.png head.png induct.png keys.png less.png link.png load.png login.png logout.png makemore.png maker.png map.png mash.png meep.png mem.png minions.png minus.png mob.png more.png msg.png new.png online.png owner.png pass2.png pass.png plus.png popular.png p.png prime.png pushfam.png pushnom.png q.png rand.png r.png save.png score.png script.png send.png sh.png small_nom.png small_pass.png spawn.png stop.png switch.png top.png tribe.png unmap.png upload.png who.png wtf1.png wtf2.png wtf3.png wtf4.png wtf5.png wtf6.png wtf7.png wtf8.png xform.png

all: $(PNGS)

.PHONY: clean
clean:
	rm -f $(PNGS) tmp.*.ppm

small_nom.png:
	echo nom | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 8 | pnmtopng -interlace > $@
small_pass.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 8 | pnmtopng -interlace > $@
pass.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
pass2.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | ppmtopgm |pnmtopng -interlace > $@
encode.png:
	echo encode | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
upload.png:
	echo upload | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
load.png:
	echo load | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
save.png:
	echo save | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
grid.png:
	echo grid | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
head.png:
	echo head | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
boss.png:
	echo boss | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
crew.png:
	echo crew | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
minions.png:
	echo minions | ../morktxt --height 3 --width 14 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
crewsize.png:
	echo crewsize | ../morktxt --height 3 --width 16 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
logout.png:
	echo logout | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
login.png:
	echo login | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@

clear.png:
	echo clear | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
close.png:
	echo close | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
go.png:
	echo go | ../morktxt --height 3 --width 4 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
stop.png:
	echo stop | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@

fam.png:
	echo fam | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
rand.png:
	echo rand | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
file.png:
	echo file | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
frens.png:
	echo frens | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
gen_nom.png:
	echo 'gen nom' | ../morktxt --height 3 --width 14 | pnmscale 12 | pnmtopng -interlace > $@
doc.png:
	echo doc | ../morktxt --height 3 --width 6 | pnmscale 12 | pnmtopng -interlace > $@
don.png:
	echo don | ../morktxt --height 3 --width 6 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
xform.png:
	echo xform | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
get.png:
	echo get | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
cam.png:
	echo cam | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
msg.png:
	echo msg | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
who.png:
	echo who | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
new.png:
	echo new | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
enc.png:
	echo enc | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
mem.png:
	echo mem | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
conf.png:
	echo conf | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
sh.png:
	echo sh | ../morktxt --height 3 --width 4 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
send.png:
	echo send | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 16 | pnmtopng -interlace > $@
switch.png:
	echo switch | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
created.png:
	echo created | ../morktxt --height 3 --width 14 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
online.png:
	echo online | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
activity.png:
	echo activity | ../morktxt --height 3 --width 16 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
active.png:
	echo active | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
popular.png:
	echo popular | ../morktxt --height 3 --width 14 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
top.png:
	echo top | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
buy.png:
	echo buy | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
mob.png:
	echo mob | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng -interlace > $@
email.png:
	echo '<jdb1729@gmail.com>' | ../morktxt --height 3 --width 38 | pnmscale 8 | pnmtopng -interlace > $@
pushnom.png:
	echo 'pushnom' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
befren.png:
	echo 'befren' | ../morktxt --height 3 --width 12 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
dashgt.png:
	echo '->' | ../morktxt --height 3 --width 4 | pnmscale 32 | pnmtopng -interlace > $@
add.png:
	echo 'add' | ../morktxt --height 3 --width 6 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
addfren.png:
	echo 'addfren' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
keys.png:
	echo 'keys' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
fren.png:
	echo 'fren' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
pushfam.png:
	echo 'pushfam' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
capture.png:
	echo 'pushfam(4)' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@

add_to_cart.png:
	echo 'add to cart' | ../morktxt --height 3 --width 22 | pnmscale 12 | pnmtopng -interlace > $@

makemore.png:
	echo 'MakeMore Peaple v1.0' |../morktxt --height 3 --width 40 |pnmscale 16 |pnmtopng -interlace > $@


# favicon.ico:
# 	echo make |../morktxt --height 3 --width 8 |pnmcut -top 1 |pnmscale 4 > tmp.make.ppm;
# 	echo more |../morktxt --height 3 --width 8 |pnmcut -top 1 |pnmscale 4 > tmp.more.ppm;
# 	pnmcat -tb tmp.make.ppm tmp.more.ppm |pnmtopng -interlace > $@




auto.png:
	echo 'auto' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
p.png:
	echo 'p' | ../morktxt --height 3 --width 2 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
q.png:
	echo 'q' | ../morktxt --height 3 --width 2 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
r.png:
	echo 'r' | ../morktxt --height 3 --width 2 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@

map.png:
	echo 'map' | ../morktxt --height 3 --width 6 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
unmap.png:
	echo 'unmap' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
meep.png:
	echo 'meep' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
more.png:
	echo 'more' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
less.png:
	echo 'less' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
plus.png:
	echo 'plus' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
minus.png:
	echo 'minus' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
blend.png:
	echo 'blend' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
mash.png:
	echo 'mash' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
spawn.png:
	echo 'spawn' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
induct.png:
	echo 'induct' | ../morktxt --height 3 --width 12 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
claim.png:
	echo 'claim' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
tribe.png:
	echo 'tribe' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
prime.png:
	echo 'prime' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
script.png:
	echo 'script' | ../morktxt --height 3 --width 12 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
comms.png:
	echo 'comms' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
owner.png:
	echo 'owner' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale -nomix 12 | pnmtopng -interlace > $@
maker.png:
	echo 'maker' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale -nomix 12 | pnmtopng -interlace > $@
score.png:
	echo 'score' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
bread.png:
	echo 'bread' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
link.png:
	echo 'link' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@
goto.png:
	echo 'goto' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng -interlace > $@


wtf1.png:
	echo "Sorry, I can't read that!" | ../morktxt --height 3 --width 50 | pnmscale 12 | pnmtopng -interlace -transparent black > $@
wtf2.png:
	echo "Go to my file and click \"claim\"." | ../morktxt --height 3 --width 64 | pnmscale 12 | pnmtopng -interlace -transparent black > $@
wtf3.png:
	echo "What language is that?" | ../morktxt --height 3 --width 44 | pnmscale 12 | pnmtopng -interlace -transparent black > $@
wtf4.png:
	echo "I'm pleased to meet you." | ../morktxt --height 3 --width 48 | pnmscale 12 | pnmtopng -interlace -transparent black > $@
wtf5.png:
	echo "o rly" | ../morktxt --height 3 --width 10 | pnmscale 12 | pnmtopng -interlace -transparent black > $@
wtf6.png:
	echo "These are all stock responses." | ../morktxt --height 3 --width 60 | pnmscale 12 | pnmtopng -interlace -transparent black > $@
wtf7.png:
	echo "Let's be frens." | ../morktxt --height 3 --width 30 | pnmscale 12 | pnmtopng -interlace -transparent black > $@
wtf8.png:
	echo "Okay? Okay." | ../morktxt --height 3 --width 22 | pnmscale 12 | pnmtopng -interlace -transparent black > $@
