all: fam.png rand.png file.png frens.png doc.png cam.png mem.png mob.png add_fren.png gen_nom.png email.png

.PHONY: clean
clean:
	rm -f fam.png rand.png file.png frens.png doc.png cam.png mem.png mob.png

small_nom.png:
	echo nom | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 8 | pnmtopng > $@
small_pass.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 8 | pnmtopng > $@
pass.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
pass2.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | ppmtopgm |pnmtopng > $@
logout.png:
	echo logout | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
login.png:
	echo login | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@

fam.png:
	echo fam | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
rand.png:
	echo rand | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
file.png:
	echo file | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
frens.png:
	echo frens | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
gen_nom.png:
	echo 'gen nom' | ../morktxt --height 3 --width 14 | pnmscale 12 | pnmtopng > $@
doc.png:
	echo doc | ../morktxt --height 3 --width 6 | pnmscale 12 | pnmtopng > $@
xform.png:
	echo xform | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
cam.png:
	echo cam | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
msg.png:
	echo msg | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
who.png:
	echo who | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
new.png:
	echo new | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
mem.png:
	echo mem | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
conf.png:
	echo conf | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
sh.png:
	echo sh | ../morktxt --height 3 --width 4 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
send.png:
	echo send | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 16 | pnmtopng > $@
online.png:
	echo online | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
active.png:
	echo active | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
popular.png:
	echo popular | ../morktxt --height 3 --width 14 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
top.png:
	echo top | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
buy.png:
	echo buy | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
mob.png:
	echo mob | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
email.png:
	echo '<jdb1729@gmail.com>' | ../morktxt --height 3 --width 38 | pnmscale 8 | pnmtopng > $@
pushnom.png:
	echo 'pushnom' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
befren.png:
	echo 'befren' | ../morktxt --height 3 --width 12 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
dashgt.png:
	echo '->' | ../morktxt --height 3 --width 4 | pnmscale 32 | pnmtopng > $@
add.png:
	echo 'add' | ../morktxt --height 3 --width 6 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
addfren.png:
	echo 'addfren' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
fren.png:
	echo 'fren' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
pushfam.png:
	echo 'pushfam' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
capture.png:
	echo 'pushfam(4)' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@

add_to_cart.png:
	echo 'add to cart' | ../morktxt --height 3 --width 22 | pnmscale 12 | pnmtopng > $@

makemore.png:
	echo 'MakeMore Peaple v1.0' |../morktxt --height 3 --width 40 |pnmscale 16 |pnmtopng > $@




map.png:
	echo 'map' | ../morktxt --height 3 --width 6 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
unmap.png:
	echo 'unmap' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
more.png:
	echo 'more' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
less.png:
	echo 'less' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
plus.png:
	echo 'plus' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
minus.png:
	echo 'minus' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
blend.png:
	echo 'blend' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
mash.png:
	echo 'mash' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
spawn.png:
	echo 'spawn' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
claim.png:
	echo 'claim' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
bread.png:
	echo 'bread' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
goto.png:
	echo 'goto' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
