all: fam.png rand.png file.png frens.png doc.png cam.png mem.png mob.png add_fren.png gen_nom.png email.png

.PHONY: clean
clean:
	rm -f fam.png rand.png file.png frens.png doc.png cam.png mem.png mob.png

small_nom.png:
	echo nom | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 8 | pnmtopng > $@
small_pass.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 8 | pnmtopng > $@
pass.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
pass2.png:
	echo pass | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | ppmtopgm |pnmtopng > $@
encode.png:
	echo encode | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
upload.png:
	echo upload | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
load.png:
	echo load | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
save.png:
	echo save | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
head.png:
	echo head | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
boss.png:
	echo boss | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
crew.png:
	echo crew | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
minions.png:
	echo minions | ../morktxt --height 3 --width 14 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
crewsize.png:
	echo crewsize | ../morktxt --height 3 --width 16 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
logout.png:
	echo logout | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
login.png:
	echo login | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@

clear.png:
	echo clear | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
close.png:
	echo close | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
go.png:
	echo go | ../morktxt --height 3 --width 4 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
stop.png:
	echo stop | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@

fam.png:
	echo fam | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
rand.png:
	echo rand | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
file.png:
	echo file | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
frens.png:
	echo frens | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
gen_nom.png:
	echo 'gen nom' | ../morktxt --height 3 --width 14 | pnmscale 12 | pnmtopng > $@
doc.png:
	echo doc | ../morktxt --height 3 --width 6 | pnmscale 12 | pnmtopng > $@
don.png:
	echo don | ../morktxt --height 3 --width 6 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
xform.png:
	echo xform | ../morktxt --height 3 --width 10 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
cam.png:
	echo cam | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
msg.png:
	echo msg | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
who.png:
	echo who | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
new.png:
	echo new | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
mem.png:
	echo mem | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
conf.png:
	echo conf | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
sh.png:
	echo sh | ../morktxt --height 3 --width 4 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
send.png:
	echo send | ../morktxt --height 3 --width 8 | pnmcut -top 1 |pnmscale 16 | pnmtopng > $@
switch.png:
	echo switch | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
created.png:
	echo created | ../morktxt --height 3 --width 14 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
online.png:
	echo online | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
activity.png:
	echo activity | ../morktxt --height 3 --width 16 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
active.png:
	echo active | ../morktxt --height 3 --width 12 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
popular.png:
	echo popular | ../morktxt --height 3 --width 14 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
top.png:
	echo top | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
buy.png:
	echo buy | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
mob.png:
	echo mob | ../morktxt --height 3 --width 6 | pnmcut -top 1 |pnmscale 12 | pnmtopng > $@
email.png:
	echo '<jdb1729@gmail.com>' | ../morktxt --height 3 --width 38 | pnmscale 8 | pnmtopng > $@
pushnom.png:
	echo 'pushnom' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
befren.png:
	echo 'befren' | ../morktxt --height 3 --width 12 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
dashgt.png:
	echo '->' | ../morktxt --height 3 --width 4 | pnmscale 32 | pnmtopng > $@
add.png:
	echo 'add' | ../morktxt --height 3 --width 6 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
addfren.png:
	echo 'addfren' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
fren.png:
	echo 'fren' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
pushfam.png:
	echo 'pushfam' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
capture.png:
	echo 'pushfam(4)' | ../morktxt --height 3 --width 14 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@

add_to_cart.png:
	echo 'add to cart' | ../morktxt --height 3 --width 22 | pnmscale 12 | pnmtopng > $@

makemore.png:
	echo 'MakeMore Peaple v1.0' |../morktxt --height 3 --width 40 |pnmscale 16 |pnmtopng > $@




auto.png:
	echo 'auto' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
p.png:
	echo 'p' | ../morktxt --height 3 --width 2 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
q.png:
	echo 'q' | ../morktxt --height 3 --width 2 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
r.png:
	echo 'r' | ../morktxt --height 3 --width 2 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@

map.png:
	echo 'map' | ../morktxt --height 3 --width 6 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
unmap.png:
	echo 'unmap' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
more.png:
	echo 'more' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
less.png:
	echo 'less' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
plus.png:
	echo 'plus' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
minus.png:
	echo 'minus' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
blend.png:
	echo 'blend' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
mash.png:
	echo 'mash' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
spawn.png:
	echo 'spawn' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
induct.png:
	echo 'induct' | ../morktxt --height 3 --width 12 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
claim.png:
	echo 'claim' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
tribe.png:
	echo 'tribe' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
prime.png:
	echo 'prime' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
script.png:
	echo 'script' | ../morktxt --height 3 --width 12 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
comms.png:
	echo 'comms' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
owner.png:
	echo 'owner' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale -nomix 12 | pnmtopng > $@
maker.png:
	echo 'maker' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale -nomix 12 | pnmtopng > $@
score.png:
	echo 'score' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
bread.png:
	echo 'bread' | ../morktxt --height 3 --width 10 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@
goto.png:
	echo 'goto' | ../morktxt --height 3 --width 8 | pnmcut -top 1 | pnmscale 12 | pnmtopng > $@


wtf1.png:
	echo "Sorry, I can't read that!" | ../morktxt --height 3 --width 50 | pnmscale 12 | pnmtopng -transparent black > $@
wtf2.png:
	echo "Go to my file and click \"claim\"." | ../morktxt --height 3 --width 64 | pnmscale 12 | pnmtopng -transparent black > $@
wtf3.png:
	echo "What language is that?" | ../morktxt --height 3 --width 44 | pnmscale 12 | pnmtopng -transparent black > $@
wtf4.png:
	echo "I'm pleased to meet you." | ../morktxt --height 3 --width 48 | pnmscale 12 | pnmtopng -transparent black > $@
wtf5.png:
	echo "o rly" | ../morktxt --height 3 --width 10 | pnmscale 12 | pnmtopng -transparent black > $@
wtf6.png:
	echo "These are all stock responses." | ../morktxt --height 3 --width 60 | pnmscale 12 | pnmtopng -transparent black > $@
wtf7.png:
	echo "Let's be frens." | ../morktxt --height 3 --width 30 | pnmscale 12 | pnmtopng -transparent black > $@
wtf8.png:
	echo "Okay? Okay." | ../morktxt --height 3 --width 22 | pnmscale 12 | pnmtopng -transparent black > $@
